### ISSUE TITLE
The weather is not displayed

### ISSUE THREAD

**Issue by 2StrHero** [FamousWolf/week-planner-card#58] opened 2024-05-10 10:52 UTC
```
weather:
  entity: weather.openweathermap
  showTemperature: true
  showLowTemperature: true
```
```
weather: weather.openweathermap
```
I don't have the weather displayed, and it's loading endlessly. What is the reason for this?

**Comment by FamousWolf** [comment] 2024-05-14 11:13
I'm not able to reproduce this. Do you get any JavaScript errors?

**Comment by FamousWolf** [comment] 2024-05-19 14:00
JavaScript error are not shown by default. [This documentation](https://docs.wp-rocket.me/article/1364-how-to-check-for-javascript-errors-on-your-site) explains how you can view them in Firefox, Chrome and Safari.

**Comment by 2StrHero** [comment] 2024-05-19 16:01
> JavaScript error are not shown by default. [This documentation](https://docs.wp-rocket.me/article/1364-how-to-check-for-javascript-errors-on-your-site) explains how you can view them in Firefox, Chrome and Safari.

It seems that there are quite a lot of them

![image](https://github.com/FamousWolf/week-planner-card/assets/132848118/aa3bb5db-7448-467a-8ee4-121941e417ba)

**Comment by Jab2870** [comment] 2024-05-20 12:49
Is your home assistant instance up to date? 

You should be able to click here to determine what version of home assistant you're running.


[![Open your Home Assistant instance and show your Home Assistant version information.](https://my.home-assistant.io/badges/info.svg)](https://my.home-assistant.io/redirect/info/)

**Comment by 2StrHero** [comment] 2024-05-20 19:27
> Is your home assistant instance up to date?
> 
> You should be able to click here to determine what version of home assistant you're running.
> 
> [![Open your Home Assistant instance and show your Home Assistant version information.](https://camo.githubusercontent.com/2f0b99cc90aded52b23874276ddf74d9d61e3bd871bd42987f05a1145782edeb/68747470733a2f2f6d792e686f6d652d617373697374616e742e696f2f6261646765732f696e666f2e737667)](https://my.home-assistant.io/redirect/info/)

![image](https://github.com/FamousWolf/week-planner-card/assets/132848118/cb839e01-f140-43e8-8dd1-1a6c41727871)

**Comment by FamousWolf** [comment] 2024-05-21 07:27
It looks like your weather entity doesn't support daily forecast. According to [the documentation](https://www.home-assistant.io/integrations/openweathermap/) Open Weather Map can be configured to either support hourly or daily forecast, so I'm assuming you've configured it for hourly forecast. I have no experience with Open Weather Map, so don't know how to configure it differently, but this isn't an issue with week-planner-card, so I'm closing this issue.

**Closed by FamousWolf** 2024-05-21 07:27 UTC
