### ISSUE TITLE
In v.1.9 did something change in how events are fetched?

### ISSUE THREAD

**Issue by bluk10** [FamousWolf/week-planner-card#187] opened 2024-11-16 04:58 UTC
Prior to 1.9 when my calendar would update every x seconds I would get the rotating wheel briefly and events would add or remove with little distraction. After updating to 1.9 when the rotating wheel appears the entire calendar collapses and clears out the event text for a second or so before expanding out and repopulating the events. I have changed nothing with my yaml.

**Comment by FamousWolf** [comment] 2024-11-20 14:44
Yes, something has changed, but not something that should cause this behavior. I'll look into it.

**Comment by bluk10** [comment] 2024-11-20 19:34
Thank you, I can upload a screencast if it is helpful describing better.

**Comment by bluk10** [comment] 2024-12-02 20:59
> Yes, something has changed, but not something that should cause this behavior. I'll look into it.

I rolled back to 1.8 and the issue went away. 
Appreciate the work you put into this amazing project.

**Comment by FamousWolf** [comment] 2024-12-03 11:54
I think this was also a problem before 1.9, but in 1.9 the rendering has become more complicated, so it's more noticeable. The problem is that I rerendered everything every time the loader was shown. I've changed it so that doesn't happen anymore. Full rerendering should now only happen if anything changes in the events. This has been added to the dev branch and will be included in the 1.11.0 release.

**Closed** 2024-12-03 11:59 UTC
Labels: bug, ready for release
