### ISSUE TITLE
card_mod not working

### ISSUE THREAD

**Issue by Byzza** [FamousWolf/week-planner-card#115] opened 2024-08-28 11:54 UTC
I've tried lots of different options, even starting fresh and just having the basics and I can't seem to get anything working with card_mod.

Any ideas?

HA Version: 2024.8.3
HACS Version: 2.0.0
Week-planner-card Version: 1.6
![image](https://github.com/user-attachments/assets/a12c5543-4ab9-49c4-9da5-43f6138922e4)

**Comment by FamousWolf** [comment] 2024-09-01 14:40
I can't reproduce this problem. Is card_mod working for other cards?

**Comment by dnoggle** [comment] 2024-09-04 18:52
I had the same thing happen and clearing the cache fixed it.

**Comment by saryn** [comment] 2024-09-05 06:13
I also had the same problem. Even clearing cache did not help. So I workarounded it this way:
```yaml
type: custom:mod-card
style:
  week-planner-card$: |
    .today .date {
      background-color: var(--state-active-color)
    }
card:
  type: custom:week-planner-card
  calendars:
    - entity: ...
```

**Comment by FamousWolf** [comment] 2024-10-28 16:13
As I can not reproduce this issue and there's a workaround (either clearing cache or using the `custom:mod-card` card) I'm closing this issue.

**Closed by FamousWolf** 2024-10-28 16:13 UTC
Labels: question
