### ISSUE TITLE
hideDaysWithoutEvents=true does not hide today

### ISSUE THREAD

**Issue by tde01065** [FamousWolf/week-planner-card#143] opened 2024-09-18 11:05 UTC
If hideDaysWithoutEvents=true, today is still visible even when empty. Please see screenshot for example.
Please note that the days between today (idag) and Saturday (lördag) are hidden.
![image](https://github.com/user-attachments/assets/28c89be3-cbc8-4e33-8e9b-e6981d8d4915)

Current configuration:
```
type: custom:week-planner-card
title: Siris matcher
compact: true
hideDaysWithoutEvents: true
days: 4
locale: sv
card_mod:
style: |
  .event.ongoing {
	font-weight: bold;
  }
  .event.past {
	opacity: .3;
  }
texts:
today: 'idag'
tomorrow: 'imorgon'
calendars:
- entity: calendar.women_s_volleyball_goccusports_com
```

**Comment by FamousWolf** [comment] 2024-10-14 13:27
This is by design and is mentioned in the documentation. I could however add a `hideTodayWithoutEvents` configuration.

**Comment by FamousWolf** [comment] 2024-10-28 15:08
This has been added and will be included in the 1.8.0 release.

**Closed** 2024-10-28 15:16 UTC
Labels: enhancement, ready for release

**Comment by tde01065** [comment] 2024-10-30 15:07
Great job! I missed the detail about the existing function wasn't valid for today.

**Comment by akeslo** [comment] 2025-10-27 23:44
Nevermind, looks like you need both:
    hideDaysWithoutEvents: true
    hideTodayWithoutEvents: true
